module.exports = {
  apps: [
    {
      name: "nexusbot-api",
      cwd: "./apps/api",
      script: "dist/index.js",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "production" },
      max_memory_restart: "512M",
      out_file: "../../logs/api.out.log",
      error_file: "../../logs/api.err.log",
    },
    {
      name: "nexusbot-bot",
      cwd: "./apps/bot",
      script: "dist/index.js",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "production" },
      max_memory_restart: "512M",
      out_file: "../../logs/bot.out.log",
      error_file: "../../logs/bot.err.log",
    },
    {
      name: "nexusbot-web",
      cwd: "./apps/web",
      script: "node_modules/.bin/next",
      args: "start -p 3000",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "production" },
      max_memory_restart: "512M",
      out_file: "../../logs/web.out.log",
      error_file: "../../logs/web.err.log",
    },
  ],
};
